packages:
  - 'apps/*'
  - 'packages/*'
  - 'backend'
  - 'blockchain'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bufferutil: true
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
